# Generated by Django 2.2.4 on 2019-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('in', 'Income'), ('ex', 'Expense')], default='ex', max_length=2),
        ),
    ]
