# Generated by Django 2.2.5 on 2019-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_activity_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_monthly',
            field=models.BooleanField(default=False),
        ),
    ]
